### ISSUE TITLE
Errors: Transaction does not balance

### ISSUE THREAD

**Issue by agarrharr** [pgr0ss/ynab_to_ledger#2]
I just did an import from ynab and I get: `Error: Transaction does not balance` for every transaction, and it looks like it's because every transaction is adding a `0.00` like this:

```
2017/12/31 Starting Balance
    Inflow: To be Budgeted             100.00
    PayPal     0.00

2018/01/03 Walmart
    Daily: Groceries             9.94
    Credit Card     0.00
```

**Comment by pgr0ss** [comment]
Hmm, I just did an export, ran it through this script, and I don't see any errors. Do you want to see if you can trim down your Register.csv to a few lines that reproduce the error and then post them here?

**Comment by agarrharr** [comment]
Here is a sample:

```csv
"PayPal","","12/31/2017","Starting Balance","Inflow: To be Budgeted","Inflow","To be Budgeted","",100.00,0.00,"Cleared"
"Credit Card","","01/03/2018","Walmart","Daily: Groceries","Daily","Groceries","",100.00,0.00,"Cleared"
```

**Comment by pgr0ss** [comment]
The problem seems to be that your Register.csv has `0.00` while mine has `$0.00` and I only handle the latter: https://github.com/pgr0ss/ynab_to_ledger/blob/799b5ae15fb5c515f8fe7e339411f15321b68ddd/ynab_to_ledger.rb#L38-L38

I'm not sure why yours is different but it seems like something I can easily add.

**Comment by pgr0ss** [comment]
Can you try checking out this commit to see if it fixes your problem? 298a774a4ce2c70d1f231f726f454e826cc9b33d

**Comment by agarrharr** [comment]
Yep! That totally fixes it! I was wondering why I was missing the dollar signs. This also causes the problem of not having any currency in my ledger journal, like this:

```
2017/12/31 Starting Balance
    Inflow: To be Budgeted             100.00
    PayPal     

2018/01/03 Walmart
    Daily: Groceries             9.94
    Credit Card     
```

But this is probably a separate issue.

**Comment by pgr0ss** [comment]
Yeah, that's weird. Maybe worth asking YNAB support about why your files are different?

**Comment by agarrharr** [comment]
I figured out what the issue was. It's a currency setting in ynab.

Under "Budget Settings", there is an option called "Currency Placement". I had it set to `Don't display symbol (123,456.78)`. Once I changed that to `Before amount ($123,456.78)`, it works as expected.

**Comment by pgr0ss** [comment]
Ah, interesting. Thanks!
